### ISSUE TITLE
Update Codecov global YAML

### ISSUE THREAD

**Issue by hugovk** [python/bedevere#441]
Suggestion from #432:

---

Tom from Codecov here. Just saw this PR and wanted to offer my help in case you ran into any issues.

Looking at the global yaml, I'd recommend changing to
```yaml
comment: false
coverage:
  status:
    changes: false
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
```
to get non-blocking status checks on PRs

_Originally posted by @thomasrockhu-codecov in https://github.com/python/bedevere/issues/432#issuecomment-1101448522_

---

The global YAML can be updated at https://app.codecov.io/account/gh/python/yaml

**Comment by hugovk** [comment]
I've updated the YAML to the above. For reference, here is what it was before:

```yaml
comment: false
coverage:
  status:
    changes: false
    patch: false
    project: false
```

**Comment by hugovk** [comment]
I created https://github.com/python/bedevere/pull/442 and coverage was sent to Codecov: https://codecov.io/gh/python/bedevere/commit/98bca146646c8bd29f3b6cd25c6dc4193e412046/

But no comment was created.

The repo`.github/.codecov.yml` is:

```yaml
comment: true
```

https://app.codecov.io/gh/python/bedevere/commit/98bca146646c8bd29f3b6cd25c6dc4193e412046 shows the combined YAML:

```yaml
codecov:
  require_ci_to_pass: true
comment: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
github_checks:
  annotations: true
```

@thomasrockhu-codecov Do you know what we're missing?
